# Example configuration for the collector example service.

[DEFAULT]
loglevel = INFO
# Log to stderr (captured by systemd/journald). true/false.
logstdout = true

[dbus]
bus_prefix = org.pympacds.test
discovery_enabled = true
